#ifndef APP_STATE_HPP
#define APP_STATE_HPP

//TODO MAKE USE OF PAUSED & LOADING
enum class AppState
{
    UNINITIALIZED,
    INITIALIZED,
    MENU,
    LOADING,
    PLAYING,
    PAUSED,
    SHUTTING_DOWN
};

#endif // APP_STATE_HPP